<?php
/**
 *
 * SugarCRM Community Edition is a customer relationship management program developed by
 * SugarCRM, Inc. Copyright (C) 2004-2013 SugarCRM Inc.
 *
 * SuiteCRM is an extension to SugarCRM Community Edition developed by SalesAgility Ltd.
 * Copyright (C) 2011 - 2018 SalesAgility Ltd.
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License version 3 as published by the
 * Free Software Foundation with the addition of the following permission added
 * to Section 15 as permitted in Section 7(a): FOR ANY PART OF THE COVERED WORK
 * IN WHICH THE COPYRIGHT IS OWNED BY SUGARCRM, SUGARCRM DISCLAIMS THE WARRANTY
 * OF NON INFRINGEMENT OF THIRD PARTY RIGHTS.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Affero General Public License along with
 * this program; if not, see http://www.gnu.org/licenses or write to the Free
 * Software Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301 USA.
 *
 * You can contact SugarCRM, Inc. headquarters at 10050 North Wolfe Road,
 * SW2-130, Cupertino, CA 95014, USA. or at email address contact@sugarcrm.com.
 *
 * The interactive user interfaces in modified source and object code versions
 * of this program must display Appropriate Legal Notices, as required under
 * Section 5 of the GNU Affero General Public License version 3.
 *
 * In accordance with Section 7(b) of the GNU Affero General Public License version 3,
 * these Appropriate Legal Notices must retain the display of the "Powered by
 * SugarCRM" logo and "Supercharged by SuiteCRM" logo. If the display of the logos is not
 * reasonably feasible for technical reasons, the Appropriate Legal Notices must
 * display the words "Powered by SugarCRM" and "Supercharged by SuiteCRM".
 */

$dictionary['kms_invoice_payments'] = array(
    'table' => 'kms_invoice_payments',
    'audited' => true,
    'inline_edit' => true,
    'duplicate_merge' => true,
    'fields' => array (
		//All Custom Fields
		'name' => 
		array (
		  'name' => 'name',
		  'vname' => 'LBL_NAME',
		  'type' => 'name',
		  'link' => true,
		  'dbType' => 'varchar',
		  'len' => '255',
		  'unified_search' => false,
		  'full_text_search' => 
		  array (
			'boost' => 3,
		  ),
		  'required' => true,
		  'importable' => 'required',
		  'duplicate_merge' => 'disabled',
		  'merge_filter' => 'disabled',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => false,
		  'inline_edit' => true,
		  'reportable' => true,
		  'size' => '20',
		),
		'customer_name' => 
		array (
		  'required' => false,
		  'name' => 'customer_name',
		  'vname' => 'LBL_CUSTOMER_NAME',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '255',
		  'size' => '20',
		),
		'amount' => 
		array (
		  'required' => false,
		  'name' => 'amount',
		  'vname' => 'LBL_AMOUNT',
		  'type' => 'decimal',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '18',
		  'size' => '20',
		  'enable_range_search' => false,
		  'precision' => '2',
		),
		'amount_received' => 
		array (
		  'required' => true,
		  'name' => 'amount_received',
		  'vname' => 'LBL_AMOUNT_RECEIVED',
		  'type' => 'decimal',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '18',
		  'size' => '20',
		  'enable_range_search' => false,
		  'precision' => '2',
		),
		'payment_type' => 
		array (
		  'required' => false,
		  'name' => 'payment_type',
		  'vname' => 'LBL_PAYMENT_TYPE',
		  'type' => 'enum',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => 100,
		  'size' => '20',
		  'options' => 'invoice_payment_type_dom',
		  'studio' => 'visible',
		  'dependency' => false,
		),
		'date_recieved' => 
		array (
		  'required' => false,
		  'name' => 'date_recieved',
		  'vname' => 'LBL_DATE_RECIEVED',
		  'type' => 'date',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'size' => '20',
		  'enable_range_search' => false,
		  'display_default' => 'now',
		),
		'transaction_reference' => 
		array (
		  'required' => false,
		  'name' => 'transaction_reference',
		  'vname' => 'LBL_TRANSACTION_REFERENCE',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '255',
		  'size' => '20',
		),
		'bank_name' => 
		array (
		  'required' => false,
		  'name' => 'bank_name',
		  'vname' => 'LBL_BANK_NAME',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '255',
		  'size' => '20',
		),
		'cheque_number' => 
		array (
		  'required' => false,
		  'name' => 'cheque_number',
		  'vname' => 'LBL_CHEQUE_NUMBER',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '50',
		  'size' => '20',
		),
		'routing_number' => 
		array (
		  'required' => false,
		  'name' => 'routing_number',
		  'vname' => 'LBL_ROUTING_NUMBER',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '50',
		  'size' => '20',
		),
		'bank_account_number' => 
		array (
		  'required' => false,
		  'name' => 'bank_account_number',
		  'vname' => 'LBL_BANK_ACCOUNT_NUMBER',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '255',
		  'size' => '20',
		),
		'bank_account_title' => 
		array (
		  'required' => false,
		  'name' => 'bank_account_title',
		  'vname' => 'LBL_BANK_ACCOUNT_TITLE',
		  'type' => 'varchar',
		  'massupdate' => 0,
		  'no_default' => false,
		  'comments' => '',
		  'help' => '',
		  'importable' => 'true',
		  'duplicate_merge' => 'disabled',
		  'duplicate_merge_dom_value' => '0',
		  'audited' => true,
		  'inline_edit' => true,
		  'reportable' => true,
		  'unified_search' => false,
		  'merge_filter' => 'disabled',
		  'len' => '255',
		  'size' => '20',
		),
		'aos_invoices_name' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'aos_invoices_name',
			'vname' => 'LBL_AOS_INVOICES_NAME',
			'type' => 'relate',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'calculated' => false,
			'len' => '255',
			'size' => '20',
			'id_name' => 'aos_invoices_id',
			'ext2' => 'AOS_Invoices',
			'module' => 'AOS_Invoices',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),
		'aos_invoices_id' =>
		array (
			'required' => false,
			'name' => 'aos_invoices_id',
			'vname' => 'LBL_AOS_INVOICES_ID',
			'type' => 'id',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'calculated' => false,
			'len' => 36,
			'size' => '20',
		),
		'aos_invoices' => array(
			'name' => 'aos_invoices',
			'vname' => 'LBL_AOS_INVOICES',
			'type' => 'link',
			'relationship' => 'aos_invoices_kms_invoice_payments',
			'module' => 'AOS_Invoices',
			'bean_name' => 'AOS_Invoices',
			'source' => 'non-db',
		),
		'account_name' =>
		array (
			'required' => false,
			'source' => 'non-db',
			'name' => 'account_name',
			'vname' => 'LBL_ACCOUNT_NAME',
			'type' => 'relate',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => '0',
			'audited' => true,
			'reportable' => true,
			'calculated' => false,
			'len' => '255',
			'size' => '20',
			'id_name' => 'account_id',
			'ext2' => 'Accounts',
			'module' => 'Accounts',
			'rname' => 'name',
			'quicksearch' => 'enabled',
			'studio' => 'visible',
		),
		'account_id' =>
		array (
			'required' => false,
			'name' => 'account_id',
			'vname' => 'LBL_ACCOUNT_ID',
			'type' => 'id',
			'massupdate' => 0,
			'comments' => '',
			'help' => '',
			'importable' => 'true',
			'duplicate_merge' => 'disabled',
			'duplicate_merge_dom_value' => 0,
			'audited' => false,
			'reportable' => true,
			'calculated' => false,
			'len' => 36,
			'size' => '20',
		),
		'accounts' => array(
			'name' => 'accounts',
			'vname' => 'LBL_ACCOUNTS',
			'type' => 'link',
			'relationship' => 'account_kms_invoice_payments',
			'module' => 'Accounts',
			'bean_name' => 'Account',
			'source' => 'non-db',
		),
		/* 'kms_bank_accounts_name' =>
        array (
            'required' => false,
            'source' => 'non-db',
            'name' => 'kms_bank_accounts_name',
            'vname' => 'LBL_KMS_BANK_ACCOUNTS_NAME',
            'type' => 'relate',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => '0',
            'audited' => true,
            'reportable' => true,
            'calculated' => false,
            'len' => '255',
            'size' => '20',
            'id_name' => 'kms_bank_accounts_id',
            'ext2' => 'kms_bank_accounts',
            'module' => 'kms_bank_accounts',
            'rname' => 'name',
            'quicksearch' => 'enabled',
            'studio' => 'visible',
        ),
        'kms_bank_accounts_id' =>
        array (
            'required' => false,
            'name' => 'kms_bank_accounts_id',
            'vname' => 'LBL_KMS_BANK_ACCOUNTS',
            'type' => 'id',
            'massupdate' => 0,
            'comments' => '',
            'help' => '',
            'importable' => 'true',
            'duplicate_merge' => 'disabled',
            'duplicate_merge_dom_value' => 0,
            'audited' => false,
            'reportable' => true,
            'calculated' => false,
            'len' => 36,
            'size' => '20',
        ), */
		
	), //End Field defs
    'relationships' => array (
	),
    'optimistic_locking' => true,
    'unified_search' => true,
);
if (!class_exists('VardefManager')) {
        require_once('include/SugarObjects/VardefManager.php');
}
VardefManager::createVardef('kms_invoice_payments', 'kms_invoice_payments', array('basic','assignable','security_groups'));